# Generated by Django 3.2.7 on 2022-02-04 02:53

import cloudinary.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='body',
            field=models.CharField(
                blank=True, db_index=True, max_length=140, null=True, verbose_name='Body'),
        ),
        migrations.AddField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created datetime'),
            preserve_default=False,
        ),

        migrations.AddField(
            model_name='post',
            name='image',
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, verbose_name='image'
            )
        ),

        migrations.AddField(
            model_name='post',
            name='like_count',
            field=models.PositiveBigIntegerField(
                blank=True, default=0, verbose_name='like_count'
            )
        ),
    ]
