# Generated by Django 3.2.7 on 2022-02-07 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20220204_0253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='created at',
        ),
    ]
